import Foundation
import JavaScriptKit

struct WebKeyboardInput {
    static func payload(of jsEvent: JSValue) -> KeyboardEventPayload {
        let eventType: KeyboardEventPayload.EventType = switch jsEvent.type.string! {
            case "keydown": jsEvent.repeat.boolean! ? .keyRepeat : .keyDown
            case "keyup": .keyUp
            default: fatalError("Unknown event type: \(jsEvent.type.string!)")
        }

        var modifiers: KeyboardEventPayload.ModifierKeys = []
        if jsEvent.shiftKey.boolean ?? false { modifiers.insert(.shift) }
        if jsEvent.ctrlKey.boolean ?? false { modifiers.insert(.control) }
        if jsEvent.altKey.boolean ?? false { modifiers.insert(.alt) }

        let key = _physicalKey(of: jsEvent.code.string!)
        let text = _jsKeyIsNonPrintableSet.contains(jsEvent.key.string!) ? nil : jsEvent.key.string

        return KeyboardEventPayload(eventType: eventType, modifiers: modifiers, key: key, text: text)
    }

    private static func _physicalKey(of jsKey: String) -> KeyboardEventPayload.PhysicalKey? {
        if let key = _jsCodeToPhysicalKeyMap[jsKey] {
            return key
        }
        return nil
    }

    private static let _jsCodeToPhysicalKeyMap: [String: KeyboardEventPayload.PhysicalKey] = [
        // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values
        // Modifier keys
        // case alt(Location)
        "AltLeft": .alt(.left),
        "AltRight": .alt(.right),
        // case control(Location)
        "ControlLeft": .control(.left),
        "ControlRight": .control(.right),
        // case shift(Location)
        "ShiftLeft": .shift(.left),
        "ShiftRight": .shift(.right),
        
        // Special keys
        // case escape
        "Escape": .escape,
        // case function(Int) // F1, F2, ..., F12, ...
        "F1": .function(1),
        "F2": .function(2),
        "F3": .function(3),
        "F4": .function(4),
        "F5": .function(5),
        "F6": .function(6),
        "F7": .function(7),
        "F8": .function(8),
        "F9": .function(9),
        "F10": .function(10),
        "F11": .function(11),
        "F12": .function(12),
        "F13": .function(13),
        "F14": .function(14),
        "F15": .function(15),
        "F16": .function(16),
        "F17": .function(17),
        "F18": .function(18),
        "F19": .function(19),
        "F20": .function(20),
        // case tab; case space
        "Tab": .tab,
        "Space": .space,
        // case backspace; case delete
        "Backspace": .backspace,
        "Delete": .delete,
        // case enter
        "Enter": .enter,
        // case arrowLeft; case arrowRight; case arrowUp; case arrowDown
        "ArrowLeft": .arrowLeft,
        "ArrowRight": .arrowRight,
        "ArrowUp": .arrowUp,
        "ArrowDown": .arrowDown,
        // case pageUp; case pageDown
        "PageUp": .pageUp,
        "PageDown": .pageDown,
        // case home; case end
        "Home": .home,
        "End": .end,
        
        // Special characters with a physical key code
        // case backquote                              // left of '1'
        "Backquote": .backquote,
        // case intlBackslash                          // left of 'Z'
        "IntlBackslash": .intlBackslash,
        // case minus; case equal                      // right of '0'
        "Minus": .minus,
        "Equal": .equal,
        // case leftBracket; case rightBracket         // right of 'P'
        "BracketLeft": .leftBracket,
        "BracketRight": .rightBracket,
        // case semicolon; case quote; case backslash  // right of 'L'
        "Semicolon": .semicolon,
        "Quote": .quote,
        "Backslash": .backslash,
        // case comma; case period; case slash         // right of 'M'
        "Comma": .comma,
        "Period": .period,
        "Slash": .slash,

        // Digits and letters
        // case digit(Int)
        "Digit1": .digit(1),
        "Digit2": .digit(2),
        "Digit3": .digit(3),
        "Digit4": .digit(4),
        "Digit5": .digit(5),
        "Digit6": .digit(6),
        "Digit7": .digit(7),
        "Digit8": .digit(8),
        "Digit9": .digit(9),
        "Digit0": .digit(0),
        // case a; case b; case c; case d; case e; case f; case g; case h; case i; case j
        // case k; case l; case m; case n; case o; case p; case q; case r; case s; case t
        // case u; case v; case w; case x; case y; case z;
        "KeyA": .a,
        "KeyB": .b,
        "KeyC": .c,
        "KeyD": .d,
        "KeyE": .e,
        "KeyF": .f,
        "KeyG": .g,
        "KeyH": .h,
        "KeyI": .i,
        "KeyJ": .j,
        "KeyK": .k,
        "KeyL": .l,
        "KeyM": .m,
        "KeyN": .n,
        "KeyO": .o,
        "KeyP": .p,
        "KeyQ": .q,
        "KeyR": .r,
        "KeyS": .s,
        "KeyT": .t,
        "KeyU": .u,
        "KeyV": .v,
        "KeyW": .w,
        "KeyX": .x,
        "KeyY": .y,
        "KeyZ": .z,

        // Numpad (not supported yet)
        "NumpadEnter": .enter,

    ]

    private static let _jsKeyIsNonPrintableSet: Set<String> = [
        // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values
        // Special values
        "Unidentified",
        // Modifier keys
        "Alt",
        "AltGraph",
        "CapsLock",
        "Control",
        "Fn",
        "FnLock",
        "Hyper",
        "Meta",
        "NumLock",
        "ScrollLock",
        "Shift",
        "Super",
        "Symbol",
        "SymbolLock",
        // Whitespace keys
        "Enter",
        "Tab",
        // Navigation keys
        "ArrowDown",
        "ArrowLeft",
        "ArrowRight",
        "ArrowUp",
        "End",
        "Home",
        "PageDown",
        "PageUp",
        // Editing keys
        "Backspace",
        "Clear",
        "Copy",
        "CrSel",
        "Cut",
        "Delete",
        "EraseEof",
        "ExSel",
        "Insert",
        "Paste",
        "Redo",
        "Undo",
        // UI keys
        "Accept",
        "Again",
        "Attn",
        "Cancel",
        "ContextMenu",
        "Escape",
        "Execute",
        "Find",
        "Finish",
        "Help",
        "Pause",
        "Play",
        "Props",
        "Select",
        "ZoomIn",
        "ZoomOut",
        // Device keys
        "BrightnessDown",
        "BrightnessUp",
        "Eject",
        "LogOff",
        "Power",
        "PowerOff",
        "PrintScreen",
        "Hibernate",
        "Standby",
        "WakeUp",
        // IME and composition keys
        "AllCandidates",
        "Alphanumeric",
        "CodeInput",
        "Compose",
        "Convert",
        "Dead",
        "FinalMode",
        "GroupFirst",
        "GroupLast",
        "GroupNext",
        "GroupPrevious",
        "ModeChange",
        "NextCandidate",
        "NonConvert",
        "PreviousCandidate",
        "Process",
        "SingleCandidate",
        // Korean keyboards only
        "HangulMode",
        "HanjaMode",
        "JunjaMode",
        // Japanese keyboards only
        "Eisu",
        "Hankaku",
        "Hiragana",
        "HiraganaKatakana",
        "KanaMode",
        "KanjiMode",
        "Katakana",
        "Romaji",
        "Zenkaku",
        "ZenkakuHankaku",
        // Function keys
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F20",
        "Soft1",
        "Soft2",
        "Soft3",
        "Soft4",
        // Phone keys
        "AppSwitch",
        "Call",
        "Camera",
        "CameraFocus",
        "EndCall",
        "GoBack",
        "GoHome",
        "HeadsetHook",
        "LastNumberRedial",
        "Notification",
        "MannerMode",
        "VoiceDial",
        // Multimedia keys
        "ChannelDown",
        "ChannelUp",
        "MediaFastForward",
        "MediaPause",
        "MediaPlay",
        "MediaPlayPause",
        "MediaRecord",
        "MediaRewind",
        "MediaStop",
        "MediaTrackNext",
        "MediaTrackPrevious",
        // Audio control keys
        "AudioBalanceLeft",
        "AudioBalanceRight",
        "AudioBassDown",
        "AudioBassBoostDown",
        "AudioBassBoostToggle",
        "AudioBassBoostUp",
        "AudioBassUp",
        "AudioFaderFront",
        "AudioFaderRear",
        "AudioSurroundModeNext",
        "AudioTrebleDown",
        "AudioTrebleUp",
        "AudioVolumeDown",
        "AudioVolumeMute",
        "AudioVolumeUp",
        "MicrophoneToggle",
        "MicrophoneVolumeDown",
        "MicrophoneVolumeMute",
        "MicrophoneVolumeUp",
        // TV control keys
        "TV",
        "TV3DMode",
        "TVAntennaCable",
        "TVAudioDescription",
        "TVAudioDescriptionMixDown",
        "TVAudioDescriptionMixUp",
        "TVContentsMenu",
        "TVDataService",
        "TVInput",
        "TVInputComponent1",
        "TVInputComponent2",
        "TVInputComposite1",
        "TVInputComposite2",
        "TVInputHDMI1",
        "TVInputHDMI2",
        "TVInputHDMI3",
        "TVInputHDMI4",
        "TVInputVGA1",
        "TVMediaContext",
        "TVNetwork",
        "TVNumberEntry",
        "TVPower",
        "TVRadioService",
        "TVSatellite",
        "TVSatelliteBS",
        "TVSatelliteCS",
        "TVSatelliteToggle",
        "TVTerrestrialAnalog",
        "TVTerrestrialDigital",
        "TVTimer",
        // Media controller keys
        "AVRInput",
        "AVRPower",
        "ColorF0Red",
        "ColorF1Green",
        "ColorF2Yellow",
        "ColorF3Blue",
        "ColorF4Grey",
        "ColorF5Brown",
        "ClosedCaptionToggle",
        "Dimmer",
        "DisplaySwap",
        "DVR",
        "Exit",
        "FavoriteClear0",
        "FavoriteClear1",
        "FavoriteClear2",
        "FavoriteClear3",
        "FavoriteRecall0",
        "FavoriteRecall1",
        "FavoriteRecall2",
        "FavoriteRecall3",
        "FavoriteStore0",
        "FavoriteStore1",
        "FavoriteStore2",
        "FavoriteStore3",
        "Guide",
        "GuideNextDay",
        "GuidePreviousDay",
        "Info",
        "InstantReplay",
        "Link",
        "ListProgram",
        "LiveContent",
        "Lock",
        "MediaApps",
        "MediaAudioTrack",
        "MediaLast",
        "MediaSkipBackward",
        "MediaSkipForward",
        "MediaStepBackward",
        "MediaStepForward",
        "MediaTopMenu",
        "NavigateIn",
        "NavigateNext",
        "NavigateOut",
        "NavigatePrevious",
        "NextFavoriteChannel",
        "NextUserProfile",
        "OnDemand",
        "Pairing",
        "PinPDown",
        "PinPMove",
        "PinPToggle",
        "PinPUp",
        "PlaySpeedDown",
        "PlaySpeedReset",
        "PlaySpeedUp",
        "RandomToggle",
        "RcLowBattery",
        "RecordSpeedNext",
        "RfBypass",
        "ScanChannelsToggle",
        "ScreenModeNext",
        "Settings",
        "SplitScreenToggle",
        "STBInput",
        "STBPower",
        "Subtitle",
        "Teletext",
        "VideoModeNext",
        "Wink",
        "ZoomToggle",
        // Speech recognition keys
        "SpeechCorrectionList",
        "SpeechInputToggle",
        // Document keys
        "Close",
        "New",
        "Open",
        "Print",
        "Save",
        "SpellCheck",
        "MailForward",
        "MailReply",
        "MailSend",
        // Application selector keys
        "LaunchCalculator",
        "LaunchCalendar",
        "LaunchContacts",
        "LaunchMail",
        "LaunchMediaPlayer",
        "LaunchMusicPlayer",
        "LaunchMyComputer",
        "LaunchPhone",
        "LaunchScreenSaver",
        "LaunchSpreadsheet",
        "LaunchWebBrowser",
        "LaunchWebCam",
        "LaunchWordProcessor",
        "LaunchApplication1",
        "LaunchApplication2",
        "LaunchApplication3",
        "LaunchApplication4",
        "LaunchApplication5",
        "LaunchApplication6",
        "LaunchApplication7",
        "LaunchApplication8",
        "LaunchApplication9",
        "LaunchApplication10",
        "LaunchApplication11",
        "LaunchApplication12",
        "LaunchApplication13",
        "LaunchApplication14",
        "LaunchApplication15",
        "LaunchApplication16",
        // Browser control keys
        "BrowserBack",
        "BrowserFavorites",
        "BrowserForward",
        "BrowserHome",
        "BrowserRefresh",
        "BrowserSearch",
        "BrowserStop",
        // Numeric keypad keys
        "Decimal",
        "Key11",
        "Key12",
        "Multiply",
        "Add",
        "Clear",
        "Divide",
        "Subtract",
        "Separator",
    ]
}
